theme: jekyll-theme-minimal
title: Dana Ionita
description: Data Analyst
logo: images/Dana_Ionita.PNG
show_downloads: false
link: (https://www.codingwithricky.com/2021/05/10/intro-to-github-pages-create-a-simple-and-free-personal-website/)

