theme: jekyll-theme-minimal
title: Dana Ionita
description: Data Analyst
logo: images/Dana_Ionita.PNG
show_downloads: false
url: https://danaionita.github.io/data_analysis_project_1.github.io
baseurl: Excel%20Projects%20Examples
