theme: jekyll-theme-minimal
title: Dana Ionita
description: Data Analyst
logo: images/Dana_Ionita.PNG
show_downloads: false
[Excel project]: ({{https://danaionita.github.io/data_analysis_project_1}}{{/blob/main/}}/Excel%20Projects%20Examples/Excel_Project_Movies_Database.xlsx)
