theme: jekyll-theme-minimal
title: Dana Ionita
description: Data Analyst
logo: images/Dana_Ionita.PNG
show_downloads: false
[Excel projects]: (https://github.com/danaionita/data_analysis_project_1.github.io/blob/main/Excel%20Projects%20Examples)
